name: Test and Deploy

on:
 push:
   branches:
     - master
 pull_request:

jobs:
  test-client:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./client/go.mod
          cache-dependency-path: ./client/go.sum
  
      - name: Run Go client tests
        working-directory: ./client
        run: go test ./...

  test-server:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./server/go.mod
          cache-dependency-path: ./server/go.sum
  
      - name: Run Go server tests
        working-directory: ./server
        run: go test ./...

  test-worker:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./worker/go.mod
          cache-dependency-path: ./worker/go.sum
  
      - name: Run Go worker tests
        working-directory: ./worker
        run: go test ./...

  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: [test-client, test-server, test-worker]
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v6

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v6
        with:
          context: ./client
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:client
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:client-${{ github.sha }}

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./server
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:server
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:server-${{ github.sha }}

      - name: Build and push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:worker
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_HUB_REPO }}:worker-${{ github.sha }}
